
export const countries = [
  { id: 'AT', label: 'Austria' },
  { id: 'BE', label: 'Belgium' },
  { id: 'BG', label: 'Bulgaria' },
  { id: 'HR', label: 'Croatia' },
  { id: 'CY', label: 'Cyprus' },
  { id: 'CZ', label: 'Czech Republic' },
  { id: 'DK', label: 'Denmark' },
  { id: 'EE', label: 'Estonia' },
  { id: 'FI', label: 'Finland' },
  { id: 'FR', label: 'France' },
  { id: 'DE', label: 'Germany' },
  { id: 'GR', label: 'Greece' },
  { id: 'HU', label: 'Hungary' },
  { id: 'IE', label: 'Ireland' },
  { id: 'IT', label: 'Italy' },
  { id: 'LV', label: 'Latvia' },
  { id: 'LT', label: 'Lithuania' },
  { id: 'LU', label: 'Luxembourg' },
  { id: 'MT', label: 'Malta' },
  { id: 'NL', label: 'Netherlands' },
  { id: 'PL', label: 'Poland' },
  { id: 'PT', label: 'Portugal' },
  { id: 'RO', label: 'Romania' },
  { id: 'SK', label: 'Slovakia' },
  { id: 'SI', label: 'Slovenia' },
  { id: 'ES', label: 'Spain' },
  { id: 'SE', label: 'Sweden' },
  { id: 'GB', label: 'United Kingdom' },
  { id: 'US', label: 'United States' },
  { id: 'JP', label: 'Japan' },
  { id: 'CN', label: 'China' },
  { id: 'CH', label: 'Switzerland' },
  { id: 'CA', label: 'Canada' },
  { id: 'AU', label: 'Australia' },
  { id: 'NO', label: 'Norway' }
];
