
export const countries = [
  { id: 'eba_GA:AL', label: 'ALBANIA' },
  { id: 'eba_GA:AT', label: 'AUSTRIA' },
  { id: 'eba_GA:BE', label: 'BELGIUM' },
  { id: 'eba_GA:BG', label: 'BULGARIA' },
  { id: 'eba_GA:CY', label: 'CYPRUS' },
  { id: 'eba_GA:CZ', label: 'CZECH REPUBLIC' },
  { id: 'eba_GA:DK', label: 'DENMARK' },
  { id: 'eba_GA:EE', label: 'ESTONIA' },
  { id: 'eba_GA:FI', label: 'FINLAND' },
  { id: 'eba_GA:FR', label: 'FRANCE' },
  { id: 'eba_GA:DE', label: 'GERMANY' },
  { id: 'eba_GA:GR', label: 'GREECE' },
  { id: 'eba_GA:HU', label: 'HUNGARY' },
  { id: 'eba_GA:IE', label: 'IRELAND' },
  { id: 'eba_GA:IT', label: 'ITALY' },
  { id: 'eba_GA:JP', label: 'JAPAN' },
  { id: 'eba_GA:XK', label: 'KOSOVO' },
  { id: 'eba_GA:LV', label: 'LATVIA' },
  { id: 'eba_GA:LT', label: 'LITHUANIA' },
  { id: 'eba_GA:LU', label: 'LUXEMBOURG' },
  { id: 'eba_GA:MK', label: 'NORTH MACEDONIA' },
  { id: 'eba_GA:MT', label: 'MALTA' },
  { id: 'eba_GA:NL', label: 'NETHERLANDS' },
  { id: 'eba_GA:NO', label: 'NORWAY' },
  { id: 'eba_GA:PL', label: 'POLAND' },
  { id: 'eba_GA:PT', label: 'PORTUGAL' },
  { id: 'eba_GA:RO', label: 'ROMANIA' },
  { id: 'eba_GA:RU', label: 'RUSSIAN FEDERATION' },
  { id: 'eba_GA:RS', label: 'SERBIA' },
  { id: 'eba_GA:SK', label: 'SLOVAKIA' },
  { id: 'eba_GA:SI', label: 'SLOVENIA' },
  { id: 'eba_GA:ES', label: 'SPAIN' },
  { id: 'eba_GA:SE', label: 'SWEDEN' },
  { id: 'eba_GA:CH', label: 'SWITZERLAND' },
  { id: 'eba_GA:TR', label: 'TURKEY' },
  { id: 'eba_GA:UA', label: 'UKRAINE' },
  { id: 'eba_GA:GB', label: 'UNITED KINGDOM' },
  { id: 'eba_GA:US', label: 'UNITED STATES' },
  { id: 'eba_GA:AF', label: 'AFGHANISTAN' },
  { id: 'eba_GA:AX', label: 'ÅLAND ISLANDS' },
  { id: 'eba_GA:DZ', label: 'ALGERIA' },
  { id: 'eba_GA:AS', label: 'AMERICAN SAMOA' },
  { id: 'eba_GA:AD', label: 'ANDORRA' },
  { id: 'eba_GA:AO', label: 'ANGOLA' },
  { id: 'eba_GA:AI', label: 'ANGUILLA' },
  { id: 'eba_GA:AQ', label: 'ANTARCTICA' },
  { id: 'eba_GA:AG', label: 'ANTIGUA AND BARBUDA' },
  { id: 'eba_GA:AR', label: 'ARGENTINA' },
  { id: 'eba_GA:AM', label: 'ARMENIA' },
  { id: 'eba_GA:AW', label: 'ARUBA' },
  { id: 'eba_GA:AU', label: 'AUSTRALIA' },
  { id: 'eba_GA:AZ', label: 'AZERBAIJAN' },
  { id: 'eba_GA:BS', label: 'BAHAMAS' },
  { id: 'eba_GA:BH', label: 'BAHRAIN' },
  { id: 'eba_GA:BD', label: 'BANGLADESH' },
  { id: 'eba_GA:BB', label: 'BARBADOS' },
  { id: 'eba_GA:BY', label: 'BELARUS' },
  { id: 'eba_GA:BZ', label: 'BELIZE' },
  { id: 'eba_GA:BJ', label: 'BENIN' },
  { id: 'eba_GA:BM', label: 'BERMUDA' },
  { id: 'eba_GA:BT', label: 'BHUTAN' },
  { id: 'eba_GA:BO', label: 'BOLIVIA, PLURINATIONAL STATE OF' },
  { id: 'eba_GA:BQ', label: 'BONAIRE, SINT EUSTATIUS AND SABA' },
  { id: 'eba_GA:BA', label: 'BOSNIA AND HERZEGOVINA' },
  { id: 'eba_GA:BW', label: 'BOTSWANA' },
  { id: 'eba_GA:BV', label: 'BOUVET ISLAND' },
  { id: 'eba_GA:BR', label: 'BRAZIL' },
  { id: 'eba_GA:IO', label: 'BRITISH INDIAN OCEAN TERRITORY' },
  { id: 'eba_GA:BN', label: 'BRUNEI DARUSSALAM' },
  { id: 'eba_GA:BF', label: 'BURKINA FASO' },
  { id: 'eba_GA:BI', label: 'BURUNDI' },
  { id: 'eba_GA:KH', label: 'CAMBODIA' },
  { id: 'eba_GA:CM', label: 'CAMEROON' },
  { id: 'eba_GA:CA', label: 'CANADA' },
  { id: 'eba_GA:CV', label: 'CAPE VERDE' },
  { id: 'eba_GA:KY', label: 'CAYMAN ISLANDS' },
  { id: 'eba_GA:CF', label: 'CENTRAL AFRICAN REPUBLIC' },
  { id: 'eba_GA:TD', label: 'CHAD' },
  { id: 'eba_GA:CL', label: 'CHILE' },
  { id: 'eba_GA:CN', label: 'CHINA' },
  { id: 'eba_GA:CX', label: 'CHRISTMAS ISLAND' },
  { id: 'eba_GA:CC', label: 'COCOS (KEELING' },
  { id: 'eba_GA:CO', label: 'COLOMBIA' },
  { id: 'eba_GA:KM', label: 'COMOROS' },
  { id: 'eba_GA:CG', label: 'CONGO' },
  { id: 'eba_GA:CD', label: 'CONGO, THE DEMOCRATIC REPUBLIC OF THE' },
  { id: 'eba_GA:CK', label: 'COOK ISLANDS' },
  { id: 'eba_GA:CR', label: 'COSTA RICA' },
  { id: 'eba_GA:CI', label: 'CÔTE D\'IVOIRE' },
  { id: 'eba_GA:HR', label: 'CROATIA' },
  { id: 'eba_GA:CU', label: 'CUBA' },
  { id: 'eba_GA:CW', label: 'CURAÇAO' },
  { id: 'eba_GA:DJ', label: 'DJIBOUTI' },
  { id: 'eba_GA:DM', label: 'DOMINICA' },
  { id: 'eba_GA:DO', label: 'DOMINICAN REPUBLIC' },
  { id: 'eba_GA:EC', label: 'ECUADOR' },
  { id: 'eba_GA:EG', label: 'EGYPT' },
  { id: 'eba_GA:SV', label: 'EL SALVADOR' },
  { id: 'eba_GA:GQ', label: 'EQUATORIAL GUINEA' },
  { id: 'eba_GA:ER', label: 'ERITREA' },
  { id: 'eba_GA:ET', label: 'ETHIOPIA' },
  { id: 'eba_GA:FK', label: 'FALKLAND ISLANDS (MALVINAS' },
  { id: 'eba_GA:FO', label: 'FAROE ISLANDS' },
  { id: 'eba_GA:FJ', label: 'FIJI' },
  { id: 'eba_GA:GF', label: 'FRENCH GUIANA' },
  { id: 'eba_GA:PF', label: 'FRENCH POLYNESIA' },
  { id: 'eba_GA:TF', label: 'FRENCH SOUTHERN TERRITORIES' },
  { id: 'eba_GA:GA', label: 'GABON' },
  { id: 'eba_GA:GM', label: 'GAMBIA' },
  { id: 'eba_GA:GE', label: 'GEORGIA' },
  { id: 'eba_GA:GH', label: 'GHANA' },
  { id: 'eba_GA:GI', label: 'GIBRALTAR' },
  { id: 'eba_GA:GL', label: 'GREENLAND' },
  { id: 'eba_GA:GD', label: 'GRENADA' },
  { id: 'eba_GA:GP', label: 'GUADELOUPE' },
  { id: 'eba_GA:GU', label: 'GUAM' },
  { id: 'eba_GA:GT', label: 'GUATEMALA' },
  { id: 'eba_GA:GG', label: 'GUERNSEY' },
  { id: 'eba_GA:GN', label: 'GUINEA' },
  { id: 'eba_GA:GW', label: 'GUINEA-BISSAU' },
  { id: 'eba_GA:GY', label: 'GUYANA' },
  { id: 'eba_GA:HT', label: 'HAITI' },
  { id: 'eba_GA:HM', label: 'HEARD ISLAND AND MCDONALD ISLANDS' },
  { id: 'eba_GA:VA', label: 'HOLY SEE (VATICAN CITY STATE' },
  { id: 'eba_GA:HN', label: 'HONDURAS' },
  { id: 'eba_GA:HK', label: 'HONG KONG' },
  { id: 'eba_GA:IS', label: 'ICELAND' },
  { id: 'eba_GA:IN', label: 'INDIA' },
  { id: 'eba_GA:ID', label: 'INDONESIA' },
  { id: 'eba_GA:IR', label: 'IRAN, ISLAMIC REPUBLIC OF' },
  { id: 'eba_GA:IQ', label: 'IRAQ' },
  { id: 'eba_GA:IM', label: 'ISLE OF MAN' },
  { id: 'eba_GA:IL', label: 'ISRAEL' },
  { id: 'eba_GA:JM', label: 'JAMAICA' },
  { id: 'eba_GA:JE', label: 'JERSEY' },
  { id: 'eba_GA:JO', label: 'JORDAN' },
  { id: 'eba_GA:KZ', label: 'KAZAKHSTAN' },
  { id: 'eba_GA:KE', label: 'KENYA' },
  { id: 'eba_GA:KI', label: 'KIRIBATI' },
  { id: 'eba_GA:KP', label: 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF' },
  { id: 'eba_GA:KR', label: 'KOREA, REPUBLIC OF' },
  { id: 'eba_GA:KW', label: 'KUWAIT' },
  { id: 'eba_GA:KG', label: 'KYRGYZSTAN' },
  { id: 'eba_GA:LA', label: 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC' },
  { id: 'eba_GA:LB', label: 'LEBANON' },
  { id: 'eba_GA:LS', label: 'LESOTHO' },
  { id: 'eba_GA:LR', label: 'LIBERIA' },
  { id: 'eba_GA:LY', label: 'LIBYA' },
  { id: 'eba_GA:LI', label: 'LIECHTENSTEIN' },
  { id: 'eba_GA:MO', label: 'MACAO' },
  { id: 'eba_GA:MG', label: 'MADAGASCAR' },
  { id: 'eba_GA:MW', label: 'MALAWI' },
  { id: 'eba_GA:MY', label: 'MALAYSIA' },
  { id: 'eba_GA:MV', label: 'MALDIVES' },
  { id: 'eba_GA:ML', label: 'MALI' },
  { id: 'eba_GA:MH', label: 'MARSHALL ISLANDS' },
  { id: 'eba_GA:MQ', label: 'MARTINIQUE' },
  { id: 'eba_GA:MR', label: 'MAURITANIA' },
  { id: 'eba_GA:MU', label: 'MAURITIUS' },
  { id: 'eba_GA:YT', label: 'MAYOTTE' },
  { id: 'eba_GA:MX', label: 'MEXICO' },
  { id: 'eba_GA:FM', label: 'MICRONESIA, FEDERATED STATES OF' },
  { id: 'eba_GA:MD', label: 'MOLDOVA, REPUBLIC OF' },
  { id: 'eba_GA:MC', label: 'MONACO' },
  { id: 'eba_GA:MN', label: 'MONGOLIA' },
  { id: 'eba_GA:ME', label: 'MONTENEGRO' },
  { id: 'eba_GA:MS', label: 'MONTSERRAT' },
  { id: 'eba_GA:MA', label: 'MOROCCO' },
  { id: 'eba_GA:MZ', label: 'MOZAMBIQUE' },
  { id: 'eba_GA:MM', label: 'MYANMAR' },
  { id: 'eba_GA:NA', label: 'NAMIBIA' },
  { id: 'eba_GA:NR', label: 'NAURU' },
  { id: 'eba_GA:NP', label: 'NEPAL' },
  { id: 'eba_GA:NC', label: 'NEW CALEDONIA' },
  { id: 'eba_GA:NZ', label: 'NEW ZEALAND' },
  { id: 'eba_GA:NI', label: 'NICARAGUA' },
  { id: 'eba_GA:NE', label: 'NIGER' },
  { id: 'eba_GA:NG', label: 'NIGERIA' },
  { id: 'eba_GA:NU', label: 'NIUE' },
  { id: 'eba_GA:NF', label: 'NORFOLK ISLAND' },
  { id: 'eba_GA:MP', label: 'NORTHERN MARIANA ISLANDS' },
  { id: 'eba_GA:OM', label: 'OMAN' },
  { id: 'eba_GA:PK', label: 'PAKISTAN' },
  { id: 'eba_GA:PW', label: 'PALAU' },
  { id: 'eba_GA:PS', label: 'PALESTINIAN TERRITORY, OCCUPIED' },
  { id: 'eba_GA:PA', label: 'PANAMA' },
  { id: 'eba_GA:PG', label: 'PAPUA NEW GUINEA' },
  { id: 'eba_GA:PY', label: 'PARAGUAY' },
  { id: 'eba_GA:PE', label: 'PERU' },
  { id: 'eba_GA:PH', label: 'PHILIPPINES' },
  { id: 'eba_GA:PN', label: 'PITCAIRN' },
  { id: 'eba_GA:PR', label: 'PUERTO RICO' },
  { id: 'eba_GA:QA', label: 'QATAR' },
  { id: 'eba_GA:RE', label: 'RÉUNION' },
  { id: 'eba_GA:RW', label: 'RWANDA' },
  { id: 'eba_GA:BL', label: 'SAINT BARTHÉLEMY' },
  { id: 'eba_GA:SH', label: 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA' },
  { id: 'eba_GA:KN', label: 'SAINT KITTS AND NEVIS' },
  { id: 'eba_GA:LC', label: 'SAINT LUCIA' },
  { id: 'eba_GA:MF', label: 'SAINT MARTIN (FRENCH PART' },
  { id: 'eba_GA:PM', label: 'SAINT PIERRE AND MIQUELON' },
  { id: 'eba_GA:VC', label: 'SAINT VINCENT AND THE GRENADINES' },
  { id: 'eba_GA:WS', label: 'SAMOA' },
  { id: 'eba_GA:SM', label: 'SAN MARINO' },
  { id: 'eba_GA:ST', label: 'SAO TOME AND PRINCIPE' },
  { id: 'eba_GA:SA', label: 'SAUDI ARABIA' },
  { id: 'eba_GA:SN', label: 'SENEGAL' },
  { id: 'eba_GA:SC', label: 'SEYCHELLES' },
  { id: 'eba_GA:SL', label: 'SIERRA LEONE' },
  { id: 'eba_GA:SG', label: 'SINGAPORE' },
  { id: 'eba_GA:SX', label: 'SINT MAARTEN (DUTCH PART' },
  { id: 'eba_GA:SB', label: 'SOLOMON ISLANDS' },
  { id: 'eba_GA:SO', label: 'SOMALIA' },
  { id: 'eba_GA:ZA', label: 'SOUTH AFRICA' },
  { id: 'eba_GA:GS', label: 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS' },
  { id: 'eba_GA:SS', label: 'SOUTH SUDAN' },
  { id: 'eba_GA:LK', label: 'SRI LANKA' },
  { id: 'eba_GA:SD', label: 'SUDAN' },
  { id: 'eba_GA:SR', label: 'SURINAME' },
  { id: 'eba_GA:SJ', label: 'SVALBARD AND JAN MAYEN' },
  { id: 'eba_GA:SZ', label: 'SWAZILAND' },
  { id: 'eba_GA:SY', label: 'SYRIAN ARAB REPUBLIC' },
  { id: 'eba_GA:TW', label: 'TAIWAN, PROVINCE OF CHINA' },
  { id: 'eba_GA:TJ', label: 'TAJIKISTAN' },
  { id: 'eba_GA:TZ', label: 'TANZANIA, UNITED REPUBLIC OF' },
  { id: 'eba_GA:TH', label: 'THAILAND' },
  { id: 'eba_GA:TL', label: 'TIMOR-LESTE' },
  { id: 'eba_GA:TG', label: 'TOGO' },
  { id: 'eba_GA:TK', label: 'TOKELAU' },
  { id: 'eba_GA:TO', label: 'TONGA' },
  { id: 'eba_GA:TT', label: 'TRINIDAD AND TOBAGO' },
  { id: 'eba_GA:TN', label: 'TUNISIA' },
  { id: 'eba_GA:TM', label: 'TURKMENISTAN' },
  { id: 'eba_GA:TC', label: 'TURKS AND CAICOS ISLANDS' },
  { id: 'eba_GA:TV', label: 'TUVALU' },
  { id: 'eba_GA:UG', label: 'UGANDA' },
  { id: 'eba_GA:AE', label: 'UNITED ARAB EMIRATES' },
  { id: 'eba_GA:UM', label: 'UNITED STATES MINOR OUTLYING ISLANDS' },
  { id: 'eba_GA:UY', label: 'URUGUAY' },
  { id: 'eba_GA:UZ', label: 'UZBEKISTAN' },
  { id: 'eba_GA:VU', label: 'VANUATU' },
  { id: 'eba_GA:VE', label: 'VENEZUELA, BOLIVARIAN REPUBLIC OF' },
  { id: 'eba_GA:VN', label: 'VIET NAM' },
  { id: 'eba_GA:VG', label: 'VIRGIN ISLANDS, BRITISH' },
  { id: 'eba_GA:VI', label: 'VIRGIN ISLANDS, U.S.' },
  { id: 'eba_GA:WF', label: 'WALLIS AND FUTUNA' },
  { id: 'eba_GA:EH', label: 'WESTERN SAHARA' },
  { id: 'eba_GA:YE', label: 'YEMEN' },
  { id: 'eba_GA:ZM', label: 'ZAMBIA' },
  { id: 'eba_GA:ZW', label: 'ZIMBABWE' },
  { id: 'eba_GA:x28', label: 'Other Countries' }
];
