import { FormField } from './types';
import { countries } from './countries';

export const entityFormFields2: FormField[] = [
  {
    id: 'b_01.02.0010',
    label: 'LEI of the entity',
    fieldType: 'alphanumerical',
    required: true,
    placeholder: 'Enter LEI code',
    description: 'b_01.02.0010'
  },
  {
    id: 'b_01.02.0020',
    label: 'Name of the entity',
    fieldType: 'alphanumerical',
    required: true,
    placeholder: 'Enter entity name',
    description: 'b_01.02.0020'
  },
  {
    id: 'b_01.02.0030',
    label: 'Country of the entity',
    fieldType: 'country',
    required: true,
    description: 'b_01.02.0030'
  },
  {
    id: 'b_01.02.0040',
    label: 'Type of entity',
    fieldType: 'closedOptions',
    required: true,
    description: 'b_01.02.0040',
    options: [
      'Credit institution',
      'Investment firm',
      'Insurance company',
      'Pension fund',
      'Other financial entity'
    ]
  },
  {
    id: 'b_01.02.0050',
    label: 'Hierarchy of the entity within the group (where applicable)',
    fieldType: 'closedOptions',
    required: true,
    description: 'b_01.02.0050',
    options: [
      'Parent',
      'Subsidiary',
      'Branch',
      'Joint venture',
      'Special purpose entity',
      'Other'
    ]
  },
  {
    id: 'b_01.02.0060',
    label: 'LEI of the direct parent undertaking of the entity',
    fieldType: 'alphanumerical',
    required: false,
    placeholder: 'Enter parent LEI code',
    description: 'b_01.02.0060'
  },
  {
    id: 'b_01.02.0070',
    label: 'Date of last update',
    fieldType: 'date',
    required: true,
    description: 'b_01.02.0070'
  },
  {
    id: 'b_01.02.0080',
    label: 'Date of integration in the Register of information',
    fieldType: 'date',
    required: true,
    description: 'b_01.02.0080'
  },
  {
    id: 'b_01.02.0090',
    label: 'Date of deletion in the Register of information',
    fieldType: 'date',
    required: false,
    description: 'b_01.02.0090'
  },
  {
    id: 'b_01.02.0100',
    label: 'Currency',
    fieldType: 'currency',
    required: true,
    description: 'b_01.02.0100',
    options: [
      'eba_CU:AED	UAE Dirham',
      'eba_CU:AFN	Afghani',
      'eba_CU:ALL	Lek',
      'eba_CU:AMD	Armenian Dram',
      'eba_CU:ANG	Netherlands Antillean Guilder',
      'eba_CU:AOA	Kwanza',
      'eba_CU:ARS	Argentine Peso',
      'eba_CU:AUD	Australian Dollar',
      'eba_CU:AWG	Aruban Florin',
      'eba_CU:AZN	Azerbaijanian Manat',
      'eba_CU:BAM	Convertible Mark',
      'eba_CU:BBD	Barbados Dollar',
      'eba_CU:BDT	Taka',
      'eba_CU:BGN	Bulgarian Lev',
      'eba_CU:BHD	Bahraini Dinar',
      'eba_CU:BIF	Burundi Franc',
      'eba_CU:BMD	Bermudian Dollar',
      'eba_CU:BND	Brunei Dollar',
      'eba_CU:BOB	Boliviano',
      'eba_CU:BOV	Mvdol',
      'eba_CU:BRL	Brazilian Real',
      'eba_CU:BSD	Bahamian Dollar',
      'eba_CU:BTN	Ngultrum',
      'eba_CU:BWP	Pula',
      'eba_CU:BYR	Belarussian Ruble (2000 Series)',
      'eba_CU:BYN	Belarusian Ruble',
      'eba_CU:BZD	Belize Dollar',
      'eba_CU:CAD	Canadian Dollar',
      'eba_CU:CDF	Congolese Franc',
      'eba_CU:CHE	WIR Euro',
      'eba_CU:CHF	Swiss Franc',
      'eba_CU:CHW	WIR Franc',
      'eba_CU:CLF	Unidades de fomento',
      'eba_CU:CLP	Chilean Peso',
      'eba_CU:CNY	Yuan Renminbi',
      'eba_CU:COP	Colombian Peso',
      'eba_CU:COU	Unidad de Valor Real',
      'eba_CU:CRC	Costa Rican Colon',
      'eba_CU:CUC	Peso Convertible',
      'eba_CU:CUP	Cuban Peso',
      'eba_CU:CVE	Cape Verde Escudo',
      'CZK	Czech Koruna',
      'eba_CU:DJF	Djibouti Franc',
      'eba_CU:DKK	Danish Krone',
      'eba_CU:DOP	Dominican Peso',
      'eba_CU:DZD	Algerian Dinar',
      'eba_CU:EGP	Egyptian Pound',
      'eba_CU:ERN	Nakfa',
      'eba_CU:ETB	Ethiopian Birr',
      'eba_CU:EUR	Euro',
      'eba_CU:FJD	Fiji Dollar',
      'eba_CU:FKP	Falkland Islands Pound',
      'eba_CU:GBP	Pound Sterling',
      'eba_CU:GEL	Lari',
      'eba_CU:GHS	Ghana Cedi',
      'eba_CU:GIP	Gibraltar Pound',
      'eba_CU:GMD	Dalasi',
      'eba_CU:GNF	Guinea Franc',
      'eba_CU:GTQ	Quetzal',
      'eba_CU:GYD	Guyana Dollar',
      'eba_CU:HKD	Hong Kong Dollar',
      'eba_CU:HNL	Lempira',
      'eba_CU:HTG	Gourde',
      'eba_CU:HUF	Forint',
      'eba_CU:IDR	Rupiah',
      'eba_CU:ILS	New Israeli Sheqel',
      'eba_CU:INR	Indian Rupee',
      'eba_CU:IQD	Iraqi Dinar',
      'eba_CU:IRR	Iranian Rial',
      'eba_CU:ISK	Iceland Krona',
      'eba_CU:JMD	Jamaican Dollar',
      'eba_CU:JOD	Jordanian Dinar',
      'eba_CU:JPY	Yen',
      'eba_CU:KES	Kenyan Shilling',
      'eba_CU:KGS	Som',
      'eba_CU:KHR	Riel',
      'eba_CU:KMF	Comoro Franc',
      'eba_CU:KPW	North Korean Won',
      'eba_CU:KRW	Won',
      'eba_CU:KWD	Kuwaiti Dinar',
      'eba_CU:KYD	Cayman Islands Dollar',
      'eba_CU:KZT	Tenge',
      'eba_CU:LAK	Kip',
      'eba_CU:LBP	Lebanese Pound',
      'eba_CU:LKR	Sri Lanka Rupee',
      'eba_CU:LRD	Liberian Dollar',
      'eba_CU:LSL	Loti',
      'eba_CU:LTL	Lithuanian Litas',
      'eba_CU:LVL	Latvian Lats',
      'eba_CU:LYD	Libyan Dinar',
      'eba_CU:MAD	Moroccan Dirham',
      'eba_CU:MDL	Moldovan Leu',
      'eba_CU:MGA	Malagasy Ariary',
      'eba_CU:MKD	Denar',
      'eba_CU:MMK	Kyat',
      'eba_CU:MNT	Tugrik',
      'eba_CU:MOP	Pataca',
      'eba_CU:MRO	Ouguiya',
      'eba_CU:MUR	Mauritius Rupee',
      'eba_CU:MVR	Rufiyaa',
      'eba_CU:MWK	Kwacha',
      'eba_CU:MXN	Mexican Peso',
      'eba_CU:MYR	Malaysian Ringgit',
      'eba_CU:MZN	Mozambique Metical',
      'eba_CU:NAD	Namibia Dollar',
      'eba_CU:NGN	Naira',
      'eba_CU:NIO	Cordoba Oro',
      'eba_CU:NOK	Norwegian Krone',
      'eba_CU:NPR	Nepalese Rupee',
      'eba_CU:NZD	New Zealand Dollar',
      'eba_CU:OMR	Rial Omani',
      'eba_CU:PAB	Balboa',
      'eba_CU:PEN	Nuevo Sol',
      'eba_CU:PGK	Kina',
      'eba_CU:PHP	Philippine Peso',
      'eba_CU:PKR	Pakistan Rupee',
      'eba_CU:PLN	Zloty',
      'eba_CU:PYG	Guarani',
      'eba_CU:QAR	Qatari Rial',
      'eba_CU:RON	New Romanian Leu',
      'eba_CU:RSD	Serbian Dinar',
      'eba_CU:RUB	Russian Ruble',
      'eba_CU:RWF	Rwanda Franc',
      'eba_CU:SAR	Saudi Riyal',
      'eba_CU:SBD	Solomon Islands Dollar',
      'eba_CU:SCR	Seychelles Rupee',
      'eba_CU:SDG	Sudanese Pound',
      'eba_CU:SEK	Swedish Krona',
      'eba_CU:SGD	Singapore Dollar',
      'eba_CU:SHP	Saint Helena Pound',
      'eba_CU:SLL	Leone',
      'eba_CU:SOS	Somali Shilling',
      'eba_CU:SRD	Surinam Dollar',
      'eba_CU:SSP	South Sudanese Pound',
      'eba_CU:STD	Dobra',
      'eba_CU:SVC	El Salvador Colon',
      'eba_CU:SYP	Syrian Pound',
      'eba_CU:SZL	Lilangeni',
      'eba_CU:THB	Baht',
      'eba_CU:TJS	Somoni',
      'eba_CU:TMT	Turkmenistan New Manat',
      'eba_CU:TND	Tunisian Dinar',
      'eba_CU:TOP	Pa\'anga',
      'eba_CU:TRY	Turkish Lira',
      'eba_CU:TTD	Trinidad and Tobago Dollar',
      'eba_CU:TWD	New Taiwan Dollar',
      'eba_CU:TZS	Tanzanian Shilling',
      'eba_CU:UAH	Hryvnia',
      'eba_CU:UGX	Uganda Shilling',
      'eba_CU:USD	US Dollar',
      'eba_CU:UYI	Uruguay Peso en Unidades Indexadas (URUIURUI)',
      'eba_CU:UYU	Peso Uruguayo',
      'eba_CU:UZS	Uzbekistan Sum',
      'eba_CU:VEF	Bolivar',
      'eba_CU:VND	Dong',
      'eba_CU:VUV	Vatu',
      'eba_CU:WST	Tala',
      'eba_CU:XCD	East Caribbean Dollar',
      'eba_CU:YER	Yemeni Rial',
      'eba_CU:ZAR	Rand',
      'eba_CU:ZMK	Zambian Kwacha (replaced January 1, 2013)',
      'eba_CU:ZMW	Zambian Kwacha',
      'eba_CU:ZWL	Zimbabwe Dollar',
      'eba_CU:x46	Other Currency (open axis tables)',
      'eba_CU:XPF	CFP Franc',
      'eba_CU:CNH	Off-shore Yuan Renminbi'
    ]
  },
  {
    id: 'b_01.02.0110',
    label: 'Value of total assets - of the financial entity',
    fieldType: 'monetary',
    required: true,
    placeholder: 'Enter value',
    description: 'b_01.02.0110'
  }
];
