
export interface FormField {
  id: string;
  label: string;
  fieldType: 'alphanumerical' | 'country' | 'closedOptions' | 'date';
  placeholder?: string;
  required?: boolean;
  options?: string[];
  description?: string;
}

export const entityFormFields: FormField[] = [
  {
    id: 'b_01.01.0010',
    label: 'LEI of the entity maintaining the register of information',
    fieldType: 'alphanumerical',
    placeholder: 'Enter LEI code',
    required: true,
    description: 'b_01.01.0010',
  },
  {
    id: 'b_01.01.0020',
    label: 'Name of the entity',
    fieldType: 'alphanumerical',
    placeholder: 'Enter entity name',
    required: true,
    description: 'b_01.01.0020',
  },
  {
    id: 'b_01.01.0030',
    label: 'Country of the entity',
    fieldType: 'country',
    required: true,
    description: 'b_01.01.0030',
  },
  {
    id: 'b_01.01.0040',
    label: 'Type of entity',
    fieldType: 'closedOptions',
    required: true,
    description: 'b_01.01.0040',
    options: [
      '(CT:x12) Credit institutions',
      '(CT:x599) Investment firms',
      '(CT:x643) Central counterparties (CCPs)',
      '(CT:x639) Asset management companies',
      '(CT:x301) account information service providers',
      '(CT:x302) electronic money institutions',
      '(CT:x303) crypto-asset service providers',
      '(CT:x304) central security depository',
      '(CT:x305) trading venues',
      '(CT:x306) trade repositories',
      '(CT:x300) payment institution',
      '(CT:x316) other financial entity',
      '(CT:x315) securitisation repository',
      '(CT:x314) crowdfunding service providers',
      '(CT:x313) administrator of critical benchmarks',
      '(CT:x312) credit rating agency',
      '(CT:x311) institutions for occupational retirement provision',
      '(CT:x320) insurance intermediaries, reinsurance intermediaries and ancillary insurance intermediaries',
      '(CT:x309) insurance and reinsurance undertakings',
      '(CT:x308) data reporting service providers',
      '(CT:x307) managers of alternative investment funds',
      '(CT:x310) issuers of asset-referenced tokens',
    ],
  },
  {
    id: 'b_01.01.0050',
    label: 'Competent Authority',
    fieldType: 'alphanumerical',
    placeholder: 'Enter competent authority',
    required: true,
    description: 'b_01.01.0050',
  },
  {
    id: 'b_01.01.0060',
    label: 'Date of the reporting',
    fieldType: 'date',
    required: true,
    description: 'b_01.01.0060',
  },
];

// Updated list of countries for dropdown with the GA prefix format
export const countries = [
  "(GA:AL) ALBANIA",
  "(GA:AT) AUSTRIA",
  "(GA:BE) BELGIUM",
  "(GA:BG) BULGARIA",
  "(GA:CY) CYPRUS",
  "(GA:CZ) CZECH REPUBLIC",
  "(GA:DK) DENMARK",
  "(GA:EE) ESTONIA",
  "(GA:FI) FINLAND",
  "(GA:FR) FRANCE",
  "(GA:DE) GERMANY",
  "(GA:GR) GREECE",
  "(GA:HU) HUNGARY",
  "(GA:IE) IRELAND",
  "(GA:IT) ITALY",
  "(GA:JP) JAPAN",
  "(GA:XK) KOSOVO",
  "(GA:LV) LATVIA",
  "(GA:LT) LITHUANIA",
  "(GA:LU) LUXEMBOURG",
  "(GA:MK) NORTH MACEDONIA",
  "(GA:MT) MALTA",
  "(GA:NL) NETHERLANDS",
  "(GA:NO) NORWAY",
  "(GA:PL) POLAND",
  "(GA:PT) PORTUGAL",
  "(GA:RO) ROMANIA",
  "(GA:RU) RUSSIAN FEDERATION",
  "(GA:RS) SERBIA",
  "(GA:SK) SLOVAKIA",
  "(GA:SI) SLOVENIA",
  "(GA:ES) SPAIN",
  "(GA:SE) SWEDEN",
  "(GA:CH) SWITZERLAND",
  "(GA:TR) TURKEY",
  "(GA:UA) UKRAINE",
  "(GA:GB) UNITED KINGDOM",
  "(GA:US) UNITED STATES",
  "(GA:AF) AFGHANISTAN",
  "(GA:AX) ÅLAND ISLANDS",
  "(GA:DZ) ALGERIA",
  "(GA:AS) AMERICAN SAMOA",
  "(GA:AD) ANDORRA",
  "(GA:AO) ANGOLA",
  "(GA:AI) ANGUILLA",
  "(GA:AQ) ANTARCTICA",
  "(GA:AG) ANTIGUA AND BARBUDA",
  "(GA:AR) ARGENTINA",
  "(GA:AM) ARMENIA",
  "(GA:AW) ARUBA",
  "(GA:AU) AUSTRALIA",
  "(GA:AZ) AZERBAIJAN",
  "(GA:BS) BAHAMAS",
  "(GA:BH) BAHRAIN",
  "(GA:BD) BANGLADESH",
  "(GA:BB) BARBADOS",
  "(GA:BY) BELARUS",
  "(GA:BZ) BELIZE",
  "(GA:BJ) BENIN",
  "(GA:BM) BERMUDA",
  "(GA:BT) BHUTAN",
  "(GA:BO) BOLIVIA, PLURINATIONAL STATE OF",
  "(GA:BQ) BONAIRE, SINT EUSTATIUS AND SABA",
  "(GA:BA) BOSNIA AND HERZEGOVINA",
  "(GA:BW) BOTSWANA",
  "(GA:BV) BOUVET ISLAND",
  "(GA:BR) BRAZIL",
  "(GA:IO) BRITISH INDIAN OCEAN TERRITORY",
  "(GA:BN) BRUNEI DARUSSALAM",
  "(GA:BF) BURKINA FASO",
  "(GA:BI) BURUNDI",
  "(GA:KH) CAMBODIA",
  "(GA:CM) CAMEROON",
  "(GA:CA) CANADA",
  "(GA:CV) CAPE VERDE",
  "(GA:KY) CAYMAN ISLANDS",
  "(GA:CF) CENTRAL AFRICAN REPUBLIC",
  "(GA:TD) CHAD",
  "(GA:CL) CHILE",
  "(GA:CN) CHINA",
  "(GA:CX) CHRISTMAS ISLAND",
  "(GA:CC) COCOS (KEELING) ISLANDS",
  "(GA:CO) COLOMBIA",
  "(GA:KM) COMOROS",
  "(GA:CG) CONGO",
  "(GA:CD) CONGO, THE DEMOCRATIC REPUBLIC OF THE",
  "(GA:CK) COOK ISLANDS",
  "(GA:CR) COSTA RICA",
  "(GA:CI) CÔTE D'IVOIRE",
  "(GA:HR) CROATIA",
  "(GA:CU) CUBA",
  "(GA:CW) CURAÇAO",
  "(GA:DJ) DJIBOUTI",
  "(GA:DM) DOMINICA",
  "(GA:DO) DOMINICAN REPUBLIC",
  "(GA:EC) ECUADOR",
  "(GA:EG) EGYPT",
  "(GA:SV) EL SALVADOR",
  "(GA:GQ) EQUATORIAL GUINEA",
  "(GA:ER) ERITREA",
  "(GA:ET) ETHIOPIA",
  "(GA:FK) FALKLAND ISLANDS (MALVINAS)",
  "(GA:FO) FAROE ISLANDS",
  "(GA:FJ) FIJI",
  "(GA:GF) FRENCH GUIANA",
  "(GA:PF) FRENCH POLYNESIA",
  "(GA:TF) FRENCH SOUTHERN TERRITORIES",
  "(GA:GA) GABON",
  "(GA:GM) GAMBIA",
  "(GA:GE) GEORGIA",
  "(GA:GH) GHANA",
  "(GA:GI) GIBRALTAR",
  "(GA:GL) GREENLAND",
  "(GA:GD) GRENADA",
  "(GA:GP) GUADELOUPE",
  "(GA:GU) GUAM",
  "(GA:GT) GUATEMALA",
  "(GA:GG) GUERNSEY",
  "(GA:GN) GUINEA",
  "(GA:GW) GUINEA-BISSAU",
  "(GA:GY) GUYANA",
  "(GA:HT) HAITI",
  "(GA:HM) HEARD ISLAND AND MCDONALD ISLANDS",
  "(GA:VA) HOLY SEE (VATICAN CITY STATE)",
  "(GA:HN) HONDURAS",
  "(GA:HK) HONG KONG",
  "(GA:IS) ICELAND",
  "(GA:IN) INDIA",
  "(GA:ID) INDONESIA",
  "(GA:IR) IRAN, ISLAMIC REPUBLIC OF",
  "(GA:IQ) IRAQ",
  "(GA:IM) ISLE OF MAN",
  "(GA:IL) ISRAEL",
  "(GA:JM) JAMAICA",
  "(GA:JE) JERSEY",
  "(GA:JO) JORDAN",
  "(GA:KZ) KAZAKHSTAN",
  "(GA:KE) KENYA",
  "(GA:KI) KIRIBATI",
  "(GA:KP) KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF",
  "(GA:KR) KOREA, REPUBLIC OF",
  "(GA:KW) KUWAIT",
  "(GA:KG) KYRGYZSTAN",
  "(GA:LA) LAO PEOPLE'S DEMOCRATIC REPUBLIC",
  "(GA:LB) LEBANON",
  "(GA:LS) LESOTHO",
  "(GA:LR) LIBERIA",
  "(GA:LY) LIBYA",
  "(GA:LI) LIECHTENSTEIN",
  "(GA:MO) MACAO",
  "(GA:MG) MADAGASCAR",
  "(GA:MW) MALAWI",
  "(GA:MY) MALAYSIA",
  "(GA:MV) MALDIVES",
  "(GA:ML) MALI",
  "(GA:MH) MARSHALL ISLANDS",
  "(GA:MQ) MARTINIQUE",
  "(GA:MR) MAURITANIA",
  "(GA:MU) MAURITIUS",
  "(GA:YT) MAYOTTE",
  "(GA:MX) MEXICO",
  "(GA:FM) MICRONESIA, FEDERATED STATES OF",
  "(GA:MD) MOLDOVA, REPUBLIC OF",
  "(GA:MC) MONACO",
  "(GA:MN) MONGOLIA",
  "(GA:ME) MONTENEGRO",
  "(GA:MS) MONTSERRAT",
  "(GA:MA) MOROCCO",
  "(GA:MZ) MOZAMBIQUE",
  "(GA:MM) MYANMAR",
  "(GA:NA) NAMIBIA",
  "(GA:NR) NAURU",
  "(GA:NP) NEPAL",
  "(GA:NC) NEW CALEDONIA",
  "(GA:NZ) NEW ZEALAND",
  "(GA:NI) NICARAGUA",
  "(GA:NE) NIGER",
  "(GA:NG) NIGERIA",
  "(GA:NU) NIUE",
  "(GA:NF) NORFOLK ISLAND",
  "(GA:MP) NORTHERN MARIANA ISLANDS",
  "(GA:OM) OMAN",
  "(GA:PK) PAKISTAN",
  "(GA:PW) PALAU",
  "(GA:PS) PALESTINIAN TERRITORY, OCCUPIED",
  "(GA:PA) PANAMA",
  "(GA:PG) PAPUA NEW GUINEA",
  "(GA:PY) PARAGUAY",
  "(GA:PE) PERU",
  "(GA:PH) PHILIPPINES",
  "(GA:PN) PITCAIRN",
  "(GA:PR) PUERTO RICO",
  "(GA:QA) QATAR",
  "(GA:RE) RÉUNION",
  "(GA:RW) RWANDA",
  "(GA:BL) SAINT BARTHÉLEMY",
  "(GA:SH) SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA",
  "(GA:KN) SAINT KITTS AND NEVIS",
  "(GA:LC) SAINT LUCIA",
  "(GA:MF) SAINT MARTIN (FRENCH PART)",
  "(GA:PM) SAINT PIERRE AND MIQUELON",
  "(GA:VC) SAINT VINCENT AND THE GRENADINES",
  "(GA:WS) SAMOA",
  "(GA:SM) SAN MARINO",
  "(GA:ST) SAO TOME AND PRINCIPE",
  "(GA:SA) SAUDI ARABIA",
  "(GA:SN) SENEGAL",
  "(GA:SC) SEYCHELLES",
  "(GA:SL) SIERRA LEONE",
  "(GA:SG) SINGAPORE",
  "(GA:SX) SINT MAARTEN (DUTCH PART)",
  "(GA:SB) SOLOMON ISLANDS",
  "(GA:SO) SOMALIA",
  "(GA:ZA) SOUTH AFRICA",
  "(GA:GS) SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
  "(GA:SS) SOUTH SUDAN",
  "(GA:LK) SRI LANKA",
  "(GA:SD) SUDAN",
  "(GA:SR) SURINAME",
  "(GA:SJ) SVALBARD AND JAN MAYEN",
  "(GA:SZ) SWAZILAND",
  "(GA:SY) SYRIAN ARAB REPUBLIC",
  "(GA:TW) TAIWAN, PROVINCE OF CHINA",
  "(GA:TJ) TAJIKISTAN",
  "(GA:TZ) TANZANIA, UNITED REPUBLIC OF",
  "(GA:TH) THAILAND",
  "(GA:TL) TIMOR-LESTE",
  "(GA:TG) TOGO",
  "(GA:TK) TOKELAU",
  "(GA:TO) TONGA",
  "(GA:TT) TRINIDAD AND TOBAGO",
  "(GA:TN) TUNISIA",
  "(GA:TM) TURKMENISTAN",
  "(GA:TC) TURKS AND CAICOS ISLANDS",
  "(GA:TV) TUVALU",
  "(GA:UG) UGANDA",
  "(GA:AE) UNITED ARAB EMIRATES",
  "(GA:UM) UNITED STATES MINOR OUTLYING ISLANDS",
  "(GA:UY) URUGUAY",
  "(GA:UZ) UZBEKISTAN",
  "(GA:VU) VANUATU",
  "(GA:VE) VENEZUELA, BOLIVARIAN REPUBLIC OF",
  "(GA:VN) VIET NAM",
  "(GA:VG) VIRGIN ISLANDS, BRITISH",
  "(GA:VI) VIRGIN ISLANDS, U.S.",
  "(GA:WF) WALLIS AND FUTUNA",
  "(GA:EH) WESTERN SAHARA",
  "(GA:YE) YEMEN",
  "(GA:ZM) ZAMBIA",
  "(GA:ZW) ZIMBABWE",
  "(GA:x28) Other Countries"
];
