
export const licensedActivities = [
  { id: 'eba_TA:x185', label: 'Non-Life Insurance: Classes 1 and 2: \'Accident and Health Insurance\'' },
  { id: 'eba_TA:x186', label: 'Non-Life Insurance: Classes 1 (fourth indent), 3, 7 and 10: \'Motor Insurance\'' },
  { id: 'eba_TA:x187', label: 'Non-Life Insurance: Classes 1 (fourth indent), 4, 6, 7 and 12: \'Marine and Transport Insurance\'' },
  { id: 'eba_TA:x188', label: 'Non-Life Insurance: Classes 1 (fourth indent), 5, 7 and 11: \'Aviation Insurance\'' },
  { id: 'eba_TA:x189', label: 'Non-Life Insurance: Classes 8 and 9: \'Insurance against Fire and other Damage to Property\'' },
  { id: 'eba_TA:x190', label: 'Non-Life Insurance: Classes 10, 11, 12 and 13: \'Liability Insurance\'' },
  { id: 'eba_TA:x191', label: 'Non-Life Insurance: Classes 14 and 15: \'Credit and Suretyship Insurance\'' },
  { id: 'eba_TA:x192', label: 'Non-Life Insurance: All classes, at the choice of the Member States, which shall notify the other Member States and the Commission of their choice' },
  { id: 'eba_TA:x193', label: 'Life Insurance: The life insurance referred to in points (a)(i), (ii) and (iii) of Article 2(3) excluding those referred to in II and III' },
  { id: 'eba_TA:x194', label: 'Life Insurance: Marriage assurance, birth assurance' },
  { id: 'eba_TA:x195', label: 'Life Insurance: The insurance referred to in points (a)(i) and (ii) of Article 2(3), which are linked to investment funds' },
  { id: 'eba_TA:x196', label: 'Life Insurance: Permanent health insurance, referred to in point (a)(iv) of Article 2(3)' },
  { id: 'eba_TA:x197', label: 'Life Insurance: Tontines, referred to in point (b)(i) of Article 2(3)' },
  { id: 'eba_TA:x198', label: 'Life Insurance: Capital redemption operations, referred to in point (b)(ii) of Article 2(3)' },
  { id: 'eba_TA:x199', label: 'Life Insurance: Management of group pension funds, referred to in point (b)(iii) and (iv) of Article 2(3)' },
  { id: 'eba_TA:x200', label: 'Life Insurance: The operations referred to in point (b)(v) of Article 2(3)' },
  { id: 'eba_TA:x201', label: 'Life Insurance: The operations referred to in Article 2(3)(c)' },
  { id: 'eba_TA:x163', label: 'Lending activities' },
  { id: 'eba_TA:x164', label: 'Financial leasing' },
  { id: 'eba_TA:x165', label: 'Issuing and administering other means of payment' },
  { id: 'eba_TA:x166', label: 'Guarantees and commitments' },
  { id: 'eba_TA:x167', label: 'Guarantees and commitments related to securities lending and borrowing, within the meaning of point 6 of Annex I to Directive 2013/36/EU' },
  { id: 'eba_TA:x168', label: 'Trading for own account or for account of customers' },
  { id: 'eba_TA:x169', label: 'Participation in securities issues and the provision of services relating to such issues' },
  { id: 'eba_TA:x28', label: 'Payment services' },
  { id: 'eba_TA:x170', label: 'Advisory services' },
  { id: 'eba_TA:x171', label: 'Money broking' },
  { id: 'eba_TA:x172', label: 'Portfolio management and advice' },
  { id: 'eba_TA:x173', label: 'Dealing on own account' },
  { id: 'eba_TA:x174', label: 'Safekeeping and administration of securities' },
  { id: 'eba_TA:x175', label: 'Safekeeping and administration of financial instruments for the account of clients' },
  { id: 'eba_TA:x176', label: 'safe-keeping and administration in relation to shares or units of collective investment undertakings' },
  { id: 'eba_TA:x177', label: 'non-core services (safekeeping and administration in relation to units of collective investment undertakings)' },
  { id: 'eba_TA:x178', label: 'Safe custody services' },
  { id: 'eba_TA:x179', label: 'Credit reference services' },
  { id: 'eba_TA:x180', label: 'Issuing electronic money' },
  { id: 'eba_TA:x181', label: 'reception and transmission of orders for crypto-assets on behalf of clients' },
  { id: 'eba_TA:x182', label: 'Portfolio management on crypto-assets' },
  { id: 'eba_TA:x183', label: 'management of portfolios of investments (AIFMD)' },
  { id: 'eba_TA:x184', label: 'management of portfolios of investments (UCITSD)' },
  { id: 'eba_TA:x202', label: 'insurance distribution' },
  { id: 'eba_TA:x203', label: 'reinsurance distribution' },
  { id: 'eba_TA:x204', label: 'Investment services related to the underlying of the derivatives' },
  { id: 'eba_TA:x205', label: 'Retirement-benefit related operations and activities arising therefrom' },
  { id: 'eba_TA:x206', label: 'issuance of credit ratings' },
  { id: 'eba_TA:x207', label: 'administering the arrangements for determining a benchmark' },
  { id: 'eba_TA:x208', label: 'collecting, analysing or processing input data for the purpose of determining a benchmark' },
  { id: 'eba_TA:x209', label: 'determining a benchmark through the application of a formula or other method of calculation or by an assessment of input data provided for that purpose' },
  { id: 'eba_TA:x210', label: 'publication of benchmark' },
  { id: 'eba_TA:x211', label: 'Provision of crowdfunding services' },
  { id: 'eba_TA:x212', label: 'ancillary non-securitisation services' },
  { id: 'eba_TA:x213', label: 'ancillary securitisation services' },
  { id: 'eba_TA:x214', label: 'collection and maintenance of the records of derivatives (non-SFTs)' },
  { id: 'eba_TA:x215', label: 'collection and maintenance of the records of SFTs' },
  { id: 'eba_TA:x216', label: 'collection and maintenance of the records of securitisations' },
  { id: 'eba_TA:x217', label: 'activity as approved publication arrangement' },
  { id: 'eba_TA:x218', label: 'activity as consolidated tape provider' },
  { id: 'eba_TA:x219', label: 'activity as approved reporting mechanism' },
  { id: 'eba_TA:x220', label: 'Services enabling cash to be placed on a payment account as well as all the operations required for operating a payment account' },
  { id: 'eba_TA:x221', label: 'Services enabling cash withdrawals from a payment account as well as all the operations required for operating a payment account' },
  { id: 'eba_TA:x222', label: 'Execution of payment transactions, including transfers of funds on a payment account with the user\'s payment service provider or with another payment service provider' },
  { id: 'eba_TA:x223', label: 'Execution of payment transactions where the funds are covered by a credit line for a payment service user' },
  { id: 'eba_TA:x224', label: 'Issuing of payment instruments and/or acquiring of payment transactions' },
  { id: 'eba_TA:x225', label: 'Money remittance' },
  { id: 'eba_TA:x226', label: 'Payment initiation services' },
  { id: 'eba_TA:x227', label: 'Account information services' },
  { id: 'eba_TA:x228', label: 'Providing custody and administration of crypto-assets on behalf of clients' },
  { id: 'eba_TA:x229', label: 'operation of a trading platform for crypto-assets' },
  { id: 'eba_TA:x230', label: 'Operation of a Regulated Market' },
  { id: 'eba_TA:x231', label: 'exchange of crypto-assets for funds' },
  { id: 'eba_TA:x232', label: 'exchange of crypto-assets for other crypto-assets' },
  { id: 'eba_TA:x233', label: 'execution of orders for crypto-assets on behalf of clients' },
  { id: 'eba_TA:x234', label: 'placing of crypto-assets' },
  { id: 'eba_TA:x235', label: 'providing advice on crypto-assets' },
  { id: 'eba_TA:x236', label: 'providing transfer services for crypto-assets on behalf of clients' },
  { id: 'eba_TA:x237', label: 'issuance of asset-referenced tokens' },
  { id: 'eba_TA:x238', label: 'notary service' },
  { id: 'eba_TA:x239', label: 'central maintenance service' },
  { id: 'eba_TA:x240', label: 'settlement service' },
  { id: 'eba_TA:x241', label: 'Organising a securities lending mechanism, as agent among participants of a securities settlement system' },
  { id: 'eba_TA:x242', label: 'collateral management services' },
  { id: 'eba_TA:x243', label: 'general collateral management services' },
  { id: 'eba_TA:x244', label: 'Establishing CSD links, providing, maintaining or operating securities accounts in relation to the settlement service, collateral management, other ancillary services' },
  { id: 'eba_TA:x245', label: 'Settlement matching, instruction routing, trade confirmation, trade verification' },
  { id: 'eba_TA:x246', label: 'Services related to shareholders\' registers' },
  { id: 'eba_TA:x247', label: 'Supporting the processing of corporate actions, including tax, general meetings and information services' },
  { id: 'eba_TA:x248', label: 'New issue services, including allocation and management of ISIN codes and similar codes' },
  { id: 'eba_TA:x249', label: 'Instruction routing and processing, fee collection and processing and related reporting' },
  { id: 'eba_TA:x250', label: 'Providing regulatory reporting' },
  { id: 'eba_TA:x251', label: 'Providing information, data and statistics to market/census bureaus or other governmental or inter-governmental entities' },
  { id: 'eba_TA:x252', label: 'Providing IT services' },
  { id: 'eba_TA:x253', label: 'Providing cash accounts to, and accepting deposits from, participants in a securities settlement system and holders of securities accounts, within the meaning of point 1 of Annex I to Directive 2013/36/EU' },
  { id: 'eba_TA:x254', label: 'Providing cash credit for reimbursement no later than the following business day, cash lending to pre-finance corporate actions and lending securities to holders of securities accounts, within the meaning of point 2 of Annex I to Directive 2013/36/EU' },
  { id: 'eba_TA:x255', label: 'Payment services involving processing of cash and foreign exchange transactions, within the meaning of point 4 of Annex I to Directive 2013/36/EU' },
  { id: 'eba_TA:x256', label: 'Treasury activities involving foreign exchange and transferable securities related to managing participants\' long balances' },
  { id: 'eba_TA:x257', label: 'Any other NCA-permitted non-banking-type ancillary services not specified in Annex of Regulation (EU) No 909/2014 (CSDR) - Section B' },
  { id: 'eba_TA:x258', label: 'Any other NCA-permitted Banking-type ancillary services not specified in Annex of Regulation (EU) No 909/2014 (CSDR) - Section C' },
  { id: 'eba_TA:x259', label: 'interposition between counterparties' },
  { id: 'eba_TA:x260', label: 'risk management' },
  { id: 'eba_TA:x261', label: 'legal and fund management accounting services' },
  { id: 'eba_TA:x262', label: 'customer inquiries' },
  { id: 'eba_TA:x263', label: 'valuation and pricing, including tax returns' },
  { id: 'eba_TA:x264', label: 'regulatory compliance monitoring' },
  { id: 'eba_TA:x265', label: 'maintenance of unit-/shareholder register' },
  { id: 'eba_TA:x266', label: 'unit/shares issues and redemptions' },
  { id: 'eba_TA:x267', label: 'maintenance of unit-holder register' },
  { id: 'eba_TA:x268', label: 'unit issues and redemptions' },
  { id: 'eba_TA:x269', label: 'contract settlements (including certificate dispatch)' },
  { id: 'eba_TA:x270', label: 'distribution of income' },
  { id: 'eba_TA:x271', label: 'record keeping' },
  { id: 'eba_TA:x272', label: 'Marketing' },
  { id: 'eba_TA:x273', label: 'services necessary to meet the fiduciary duties of the AIFM' },
  { id: 'eba_TA:x274', label: 'investment advice concerning one or more of the instruments listed in Annex I, Section C to Directive 2004/39/EC' },
  { id: 'eba_TA:x275', label: 'Ancillary services' },
  { id: 'eba_TA:x104', label: 'Foreign exchange services' },
  { id: 'eba_TA:x133', label: 'Reception and transmission of orders' },
  { id: 'eba_TA:x134', label: 'Execution of orders on behalf of clients' },
  { id: 'eba_TA:x136', label: 'Portfolio management' },
  { id: 'eba_TA:x137', label: 'Investment advice' },
  { id: 'eba_TA:x138', label: 'Underwriting of financial instruments and/or placing of financial instruments on a firm commitment basis' },
  { id: 'eba_TA:x139', label: 'Placing of financial instruments without a firm commitment basis' },
  { id: 'eba_TA:x140', label: 'Operation of an MTF' },
  { id: 'eba_TA:x141', label: 'Operation of an OTF' },
  { id: 'eba_TA:x143', label: 'Granting credits or loans to investors' },
  { id: 'eba_TA:x144', label: 'Advice to undertakings on capital structure, industrial strategy and related matters and advice and services relating to mergers and the purchase of undertakings' },
  { id: 'eba_TA:x146', label: 'Investment research and financial analysis' },
  { id: 'eba_TA:x147', label: 'Services related to underwriting' },
  { id: 'eba_TA:x162', label: 'Taking deposits and other repayable funds' }
];
